/**
 * A highly sophisticated, conversational English-to-Hinglish translation utility
 * designed to provide natural, WhatsApp-style Hindi-English hybrid text
 * written in Roman script (Latin alphabet).
 */
export function convertToHinglish(text: string): string {
  if (!text) return "";
  
  let res = text;
  
  // Replace complete sentences/patterns to preserve high astrological authenticity
  const sentenceReplacements: [RegExp, string][] = [
    [/Inherent leaders, pioneering spirits, ambitious and fiercely independent\./gi, "Aap birth se hi leader hain, ambitious hain aur bohot independent rehna pasand karte hain."],
    [/As a Moolank 1 ruled by the Sun, you radiate warmth, authority, and creative life force\./gi, "Moolank 1 ke roop mein aap par Surya Dev ka prabhav hai, jisse aapke andar warmth, authority aur creative energy bhari hui hai."],
    [/You prefer creating your own paths rather than following others, and possess high determination\./gi, "Aap doosron ke banaye raste par chalne ke bajaye apna khud ka rasta (pioneering path) banana pasand karte hain aur aapka determination bohot strong hai."],
    [/However, you must keep ego and impatience in check\./gi, "Lekin dhyan rahe, thoda ego aur impatience par control rakhna bohot zaroori hai."],
    [/Gentle, highly intuitive, diplomatic, and deeply artistic peace-makers\./gi, "Aap gentle, highly intuitive aur dil se bohot artistic insaan hain jo sabke sath peace bana ke chalna pasand karte hain."],
    [/Ruled by the Moon, you are sensitive, empathetic, and highly cooperative\./gi, "Chandra Dev (Moon) se ruled hone ke karan aap sensitive, bohot caring aur cooperative hain."],
    [/Your mood and energy can wax and wane like the tides, making emotional balance your primary life challenge\./gi, "Aapka mood aur energy Moon ki tarah change hota rehta hai, isliye emotional balance rakhna aapka sabse bada challenge hai."],
    [/Vibrant, creative, expressive, intellectual, and naturally lucky seekers\./gi, "Aap vibrant, bohot creative aur intellectual hain jo naturally kafi lucky hote hain."],
    [/Ruled by the guru planet Jupiter, you are highly intellectual, expressive, wise, and optimistic\./gi, "Jupiter (Guru) ke asar se aap bohot gyaani, wise aur hamesha positive (optimistic) rehne wale insaan hain."],
    [/You are a natural teacher, counselor, and creative enthusiast\./gi, "Aap naturally ek acche teacher, counselor ya guide ban sakte hain."],
    [/Be mindful not to get too preachy or over-ambitious\./gi, "Dhyan rakhein ki aap bohot jyada preachy ya bina wajah gyaan dene wale na banein."],
    [/Courageous, highly energetic, protective, humanitarian, and natural warriors\./gi, "Aap bohot nidar, courageous aur pure energetic warrior hain jo hamesha sabko protect karte hain."],
    [/Ruled by Mars, you are a dynamo of pure energy, bravery, and action\./gi, "Mars (Mangal Dev) ke asar se aap bohot energetic, brave aur action-oriented insaan hain."],
    [/Your primary challenge is to redirect your fiery anger and impatience into constructive pathways\./gi, "Aapka sabse bada challenge apne gusse aur impatience ko sahi direction me channelise karna hai."],
    [/Your ruling planet is/gi, "Aapka ruling planet hai"],
    [/To align with your highest timeline/gi, "Apni highest energy se align karne ke liye"],
    [/Celestial Strengths/gi, "Cosmic Strengths (Taakat)"],
    [/Karmic Hurdle/gi, "Karmic Obstacles (Chunautiyan)"],
    [/Cosmic Sadhanas & Practical Steps/gi, "Cosmic Sadhanas aur Simple Remedies"],
    [/Planetary Remedy/gi, "Grah Upay (Remedy)"],
    [/Behavioral Calibration/gi, "Behavioral Balance"],
    [/Daily Action/gi, "Daily Activity"],
    [/Lucky Days\/Colors/gi, "Shubh Din aur Colors"],
    [/Mentor's Blessings/gi, "Guru ka Aashirwad"],
    [/Remember, your Moolank/gi, "Yaad rakhein, aapka Moolank"],
    [/Practice the Sadhana Tracker tab daily/gi, "Sadhana Tracker tab ko daily follow karein"],
    [/Let your actions match your highest blueprint!/gi, "Apne karmo ko apne highest potential se match karein!"],
    [/Today radiates solar leadership vibes\./gi, "Aaj ka din solar leadership vibes se bhara hua hai."],
    [/You possess immense clarity to kickstart/gi, "Aapke paas full clarity hai naye projects start karne ke liye."],
    [/Today focuses on structural order, balance, and fine-tuning your goals\./gi, "Aaj ka focus life me order, balance aur goals ko align karne par hai."],
    [/It is a brilliant day for planning, organizing, and counseling\./gi, "Planning, scheduling aur counseling ke liye aaj ka din bohot hi badhiya hai."]
  ];

  for (const [regex, rep] of sentenceReplacements) {
    res = res.replace(regex, rep);
  }

  // Word-by-word general astrology conversions to give it a rich Hinglish flavor
  const wordReplacements: [RegExp, string][] = [
    [/\b(is rules by|is ruled by|ruled by)\b/gi, "se ruled hai"],
    [/\b(strong leadership)\b/gi, "strong leadership quality"],
    [/\b(pioneering spirit)\b/gi, "naye raste banane ki spirit"],
    [/\b(high confidence)\b/gi, "high confidence aur self-belief"],
    [/\b(self-reliance)\b/gi, "apne dum par kaam karna"],
    [/\b(deep loyalty)\b/gi, "sachi loyalty"],
    [/\b(highly protective)\b/gi, "bohot protective nature"],
    [/\b(encouraging partner)\b/gi, "bohot supportive partner"],
    [/\b(purity of intention)\b/gi, "mann ki saaf niyat"],
    [/\b(high physical vitality)\b/gi, "kamal ki physical energy"],
    [/\b(rapid healing)\b/gi, "fast recovery aur healing"],
    [/\b(strong endurance)\b/gi, "shandaar stamina"],
    [/\b(pure clarity of vision)\b/gi, "damdaar vision aur clarity"],
    [/\b(unwavering resolve)\b/gi, "pukka irada (determination)"],
    [/\b(transformational power)\b/gi, "life badalne ki power"],
    [/\b(deep empathy)\b/gi, "deep compassion aur sensitivity"],
    [/\b(diplomatic skill)\b/gi, "sabko sath leke chalne ki skill"],
    [/\b(rich artistic imagination)\b/gi, "kamal ki creative imagination"],
    [/\b(gentle demeanor)\b/gi, "bohot hi pyara behavior"],
    [/\b(excellent team worker)\b/gi, "shandaar team player"],
    [/\b(intuitive problem solver)\b/gi, "inner intuition se problem solve karne wale"],
    [/\b(empathetic communication)\b/gi, "pyaar se baat karne ki kala"],
    [/\b(highly romantic)\b/gi, "dil se romantic"],
    [/\b(natural peacemaker)\b/gi, "natural peacemaker (sulah karwane wale)"],
    [/\b(deep intuition)\b/gi, "strong gut-feeling"],
    [/\b(lucid dreaming)\b/gi, "sach hone wale sapne"],
    [/\b(warm charisma)\b/gi, "pyara charisma"],
    [/\b(high intellect)\b/gi, "bohot hi sharp mind"],
    [/\b(expressive creativity)\b/gi, "expressive creativity aur art"],
    [/\b(optimism)\b/gi, "hamesha positive rehna (optimism)"],
    [/\b(exceptional courage)\b/gi, "nidar aur bohot hi courageous"],
    [/\b(protective heart)\b/gi, "protective dil"],
    [/\b(high vital energy)\b/gi, "bohot achhi dynamic energy"],
    [/\b(action-oriented leadership)\b/gi, "action-oriented leadership quality"],
    [/\b(fierce protection)\b/gi, "protective nature"],
    [/\b(intense passion)\b/gi, "kamal ka passion"],
    [/\b(absolute honesty)\b/gi, "poori tarah se honesty"],
    [/\b(commanding presence)\b/gi, "commanding personality"],
    [/\b(fearless execution)\b/gi, "bina darr ke kaam poora karna"],
    [/\b(physical dynamism)\b/gi, "physical fitness aur activity"],
    [/\b(dynamic selflessness)\b/gi, "selfless service"],
    [/\b(protective guardian)\b/gi, "protective guardian ya guide"],
    [/\b(immense resilience)\b/gi, "kamal ki strong energy"],
    [/\b(exceptional muscle recovery)\b/gi, "quick body recovery"],
    [/\b(high stamina)\b/gi, "bohot hi achha stamina"],
    [/\b(strong structural immunity)\b/gi, "solid immunity"],
    [/\b(fearless protection)\b/gi, "nidar bankar protect karna"],
    [/\b(dynamic transformation guide)\b/gi, "dynamic guide"],
    [/\b(humanitarian action)\b/gi, "humanitarian service"],
    [/\b(crisis leadership master)\b/gi, "crisis handle karne me expert"],
    [/\b(high athletic capacity)\b/gi, "bohot hi athletic fitness"],
    [/\b(action manifestation)\b/gi, "fast manifestation power"],
    [/\b(authoritative nature)\b/gi, "thoda dominating nature"],
    [/\b(impatience with others)\b/gi, "dusro se jaldi bore ya impatient hona"],
    [/\b(ego struggles)\b/gi, "ego aur self-respect conflicts"],
    [/\b(difficulty taking feedback)\b/gi, "doosron ki advice jaldi accept na karna"],
    [/\b(dominating tendencies)\b/gi, "partner par dominance jatana"],
    [/\b(fearing vulnerability)\b/gi, "apne emotions share karne me darna"],
    [/\b(expects constant validation)\b/gi, "hamesha appreciation chahna"],
    [/\b(stubbornness under pressure)\b/gi, "stress me ziddi ho jana"],
    [/\b(dislike of repetitive tasks)\b/gi, "daily repetitive kaam pasand na aana"],
    [/\b(friction with authority)\b/gi, "apne boss se thodi behas ho jana"],
    [/\b(status-driven spending)\b/gi, "status dikhane ke liye kharch karna"],
    [/\b(impulsive investments)\b/gi, "bina soche samjhe investment karna"],
    [/\b(overconfidence in financial recoveries)\b/gi, "money recover ho jayega - aisa overconfidence"],
    [/\b(rigidity of views)\b/gi, "apni baato par adde rehna"],
    [/\b(arrogance under stress)\b/gi, "gusse me rude ho jana"],
    [/\b(defensiveness)\b/gi, "jaldi defensive ho jana"],
    [/\b(adrenal fatigue)\b/gi, "high stress se fatigue"],
    [/\b(overheating)\b/gi, "body me heat badhna"],
    [/\b(cardiovascular strain)\b/gi, "heart beat aur BP issues"],
    [/\b(over-sensitivity)\b/gi, "bohot jaldi hurt ho jana (over-sensitive)"],
    [/\b(mood fluctuations)\b/gi, "mood swings aur irritation"],
    [/\b(lack of assertiveness)\b/gi, "apni baat sahi se na keh pana"],
    [/\b(easily influenced)\b/gi, "dusro ki baato me jaldi aana"],
    [/\b(fear of rejection)\b/gi, "rejection ka darr hona"],
    [/\b(overthinking partner's signals)\b/gi, "partner ki baato ko overthink karna"],
    [/\b(passive-aggressive reactions)\b/gi, "man me gussa rakh ke chup rehna"],
    [/\b(difficulty handling harsh criticism)\b/gi, "harsh criticism tolerate na kar pana"],
    [/\b(reluctance to compete directly)\b/gi, "direct competition se bachna"],
    [/\b(anxiety over stability)\b/gi, "future stability ki tension"],
    [/\b(financial anxiety)\b/gi, "paise ko lekar thoda stress"],
    [/\b(vague planning)\b/gi, "vague financial planning"],
    [/\b(lending money based on sentiment)\b/gi, "emotional hokar kisi ko bhi udhaar de dena"],
    [/\b(self-doubt)\b/gi, "apne aap par doubt karna"],
    [/\b(worrying about future scenarios)\b/gi, "future scenarios ko lekar tension lena"],
    [/\b(vulnerability to harsh environments)\b/gi, "negative environments se jaldi disturb hona"],
    [/\b(anxiety-driven gut issues)\b/gi, "tension me stomach kharab hona"],
    [/\b(fluid retention)\b/gi, "body me water retention"],
    [/\b(frequent colds)\b/gi, "jaldi sardi-khansi hona"],
    [/\b(sacrificing your own truth for superficial peace)\b/gi, "bahari peace ke liye apni khushi sacrifice karna"],
    [/\b(hesitation to step into power)\b/gi, "apni power me aane se ghabrana"],
    [/\b(absorbing negative energies from environments)\b/gi, "dusro ki negative energies absorb kar lena"],
    [/\b(overactive worry cycle)\b/gi, "hamesha chinta (worrying) karte rehna"],
    [/\b(over-expansion)\b/gi, "ek sath bohot saare kaam failana"],
    [/\b(scattering energies)\b/gi, "ek sath multiple cheezo me energy bikhairna"],
    [/\b(impatient with trivialities)\b/gi, "boring ya choti baato se irritate hona"],
    [/\b(extravagance)\b/gi, "showoff ya unnecessary spending"],
    [/\b(fear of being restricted)\b/gi, "freedom chin jaane ka darr"],
    [/\b(unrealistic standards)\b/gi, "partner se bohot jyada expectations rakhna"],
    [/\b(can be intellectually dismissive)\b/gi, "dusro ke brainpower ko dismiss karna"],
    [/\b(short temper)\b/gi, "bohot jaldi gussa aana"],
    [/\b(impatience)\b/gi, "impatience (bechaini)"],
    [/\b(prone to minor accidents)\b/gi, "haddi me chot ya minor cuts lagna"],
    [/\b(rigid opinionated nature)\b/gi, "apni hi opinion ko sahi manna"],
    [/\b(dominating behavior)\b/gi, "bohot dominating behavior"],
    [/\b(impulsive arguments)\b/gi, "gusse me arguments start karna"],
    [/\b(high expectations of active response)\b/gi, "partner se quick response ki expectation rakhna"],
    [/\b(friction with restrictive rules)\b/gi, "strict rules pasand na aana"],
    [/\b(impulsive decisions)\b/gi, "bina soche samjhe decisions lena"],
    [/\b(impatient communication)\b/gi, "gusse me ya jaldbazi me baat karna"],
    [/\b(lending money on impulsive promise)\b/gi, "bosh me aake kisi ko bhi paise de dena"],
    [/\b(unplanned luxury spending)\b/gi, "bina budget ke luxury shopping"],
    [/\b(speculative risks)\b/gi, "heavy risk lena"],
    [/\b(fiery impulsiveness)\b/gi, "bohot hi impulsive hona"],
    [/\b(aggressive reaction to friction)\b/gi, "thodi si bahas par aggressive ho jana"],
    [/\b(cuts and physical bruises)\b/gi, "sharir me cuts aur bruises lagna"],
    [/\b(inflammatory reactions)\b/gi, "body inflammation ya skin irritation"],
    [/\b(acidity)\b/gi, "acidity aur stomach burning"],
    [/\b(getting caught in minor personal fights)\b/gi, "fuzool ke jhagdo me apni energy waste karna"],
    [/\b(scattering fuel on minor irritants)\b/gi, "choti choti baato par gussa hokar energy waste karna"],
    
    // Mystical / Astrological enhancements
    [/\bmeditation\b/gi, "dhyan (meditation)"],
    [/\bdestiny\b/gi, "bhagya (destiny)"],
    [/\bspirituality\b/gi, "adhyatmikta (spirituality)"],
    [/\bspiritual path\b/gi, "adhyatmik rasta"],
    [/\benergy blockages\b/gi, "urja dosh (energy blockages)"],
    [/\benergy flow\b/gi, "somatic urja prabah (energy flow)"],
    [/\bplanetary vibration\b/gi, "grahon ki vibration"],
    [/\bruling planet\b/gi, "ruling grah"],
    [/\bgemstone\b/gi, "shubh ratna (gemstone)"],
    [/\bmantra chanting\b/gi, "mantra jaap"],
    [/\bkarma cycle\b/gi, "karma chakra"],
    [/\bobstacles\b/gi, "rukaavatein (hurdles)"],
    [/\bharmony\b/gi, "harmony (pyaar aur mel)"],
    [/\bsuccess\b/gi, "safalta (success)"],
    [/\bwealth status\b/gi, "financial sthiti (wealth)"],
    [/\blucky days\b/gi, "shubh din (lucky days)"],
    [/\bdivine timing\b/gi, "bhagwan ki timing (divine grace)"]
  ];

  for (const [regex, rep] of wordReplacements) {
    res = res.replace(regex, rep);
  }

  // General vocabulary polish for nice vibes
  const genericWords: [RegExp, string][] = [
    [/\b(heals|heal|healing)\b/gi, "healing"],
    [/\b(creative|creativity)\b/gi, "creative"],
    [/\b(spiritual|spirituality)\b/gi, "spiritual"],
    [/\b(energies|energy)\b/gi, "energy"],
    [/\b(leaders|leader)\b/gi, "leader"],
    [/\b(leadership)\b/gi, "leadership quality"],
    [/\b(challenges|challenge)\b/gi, "challenge"],
    [/\b(strengths|strength)\b/gi, "strengths (taakat)"],
    [/\b(remedies|remedy)\b/gi, "remedy"],
    [/\b(tips|tip)\b/gi, "tips"],
    [/\b(ambitious|ambition)\b/gi, "ambitious"],
    [/\b(independent|independence)\b/gi, "independent"],
    [/\b(confidence)\b/gi, "confidence"],
    [/\b(loyalty|loyal)\b/gi, "loyal"],
    [/\b(patience|patient)\b/gi, "patience (sabar)"],
    [/\b(empathy|empathetic)\b/gi, "empathetic (caring)"],
    [/\b(wisdom)\b/gi, "gyaan (wisdom)"],
    [/\b(harmony|harmonious)\b/gi, "harmony (pyaar-mel)"],
    [/\b(potential)\b/gi, "potential"],
    [/\b(relationships|relationship)\b/gi, "relationship"],
    [/\b(career)\b/gi, "career"]
  ];

  for (const [regex, rep] of genericWords) {
    res = res.replace(regex, rep);
  }

  return res;
}
